# -*- coding: utf-8 -*-
"""Guardar datos procesados Spark Streaming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLHAxGfd20s4RoAFci3nLxpNucHk81VK
"""

from pyspark import SparkContext
from pyspark.streaming import StreamingContext

sc = SparkContext("local[2]", "NetworkWordCount")
ssc = StreamingContext(sc, 5)

lines = ssc.socketTextStream("localhost", 9999)

words = lines.flatMap(lambda line: line.split(" "))
pairs = words.map(lambda word: (word, 1))
wordCounts = pairs.reduceByKey(lambda x, y: x + y)


output_dir = "hdfs://localhost:9870/user/alejandro/output"
wordCounts.foreachRDD(lambda rdd: rdd.saveAsTextFile(output_dir))

ssc.start()
ssc.awaitTermination()